### ISSUE TITLE
Add Lighthouse Quests

### ISSUE THREAD

**Issue by Blightbuster** [TarkovTracker/tarkovdata#169] opened 2021-12-16 01:54 UTC
Unfortunately other data like objective location etc. is still unknown at this point.
---

**Overpopulation:**
- Secure the cottage area from Scavs on Lighthouse
---
**Cargo X - Part 4:**
- Locate the TerraGroup cargo along the shore on Lighthouse
---
**Communication Difficulties:**
- Reach the trader on Lighthouse
- Survive and extract from the location
---
**Lost Contact:**
- Find the lost group in the chalet area on Lighthouse
- Survive and extract from the location
---
**Revision - Part 2:**
- Locate and mark the first BRDM with an MS2000 Marker
- Locate and mark the second BRDM with an MS2000 Marker
- Locate and mark the first Stryker with an MS2000 Marker
- Locate and mark the second Stryker with an MS2000 Marker
---
**The Hermit:**
- Find and obtain the message for Jaeger
- Locate the hideout of Jaeger's friend on Lighthouse
- Hand over the message
---
**Long Road:**
- Eliminate Scavs along the main road on Lighthouse
---
**Missing Cargo:**
- Locate the crashed helicopter on Lighthouse
- Find the informant's intelligence folder
- Hand over the folder
---
**Counteraction:**
- Hand over the found in raid BEAR PMC dogtags
- Eliminate BEAR PMC operatives all over the Lighthouse territory
---
**Corporate Secrets:**
- Find the data on water pump operation
- Find the data on pumping station operation
- Hand over the extracted data (x2)
---
**Seaside Vacation:**
- Find the informant's briefcase on Lighthouse
- Hand over the found package
---
**Energy Crisis:**
- Find and mark the group of fuel tanks with an MS2000 Marker on Lighthouse
- Find and mark the first tanker truck with an MS2000 marker on Lighthouse
- Find and mark the second tanker truck with an MS2000 marker on Lighthouse
- Find and mark the third tanker truck with an MS2000 marker on Lighthouse
---
**The Huntsman Path - Outcasts:**
- Eliminate Rogue USEC operatives
---
**Our Own Land:**
- Eliminate USEC PMC operatives all over the Lighthouse territory
- Eliminate USEC PMC operatives all over the Lighthouse territory

**Comment by thaddeus** [comment] 2021-12-18 23:27
Started adding a couple, and am just unlocking more, collecting what quests/levels are pre-requisite. Wiki has a few as well, but not everything.

**Comment by blitzmann** [comment] 2022-01-01 16:38
is there a branch for this? Don't want to attempt to add my contributions and find out "oh, these have already been documented

**Comment by thaddeus** [comment] 2022-01-01 20:38
@blitzmann There is not, so you wouldn't be duplicating any work right now. I've been working on a tool to make editing/validating the data better, but haven't had enough free time to also work on the data. If you can help out with it, it would be super appreciated!

**Comment by blitzmann** [comment] 2022-01-02 17:43
@Blightbuster Can you remove Easy Job from the ones hat need to be done? Looks like a PR was merged in recently.

https://github.com/TarkovTracker/tarkovdata/pull/194

@thaddeus I'll attempt to add some of my quests, can't promise they will be 100% complete as I don't know the level requirements or anything like that

**Comment by blitzmann** [comment] 2022-01-02 17:44
Also, how long does it take for the data to reflect in tarkov tracker?

**Comment by Shebuka** [comment] 2022-01-06 23:31
**Long Road** requires completion of **Friend from the West - Part 2**

**Comment by Shebuka** [comment] 2022-01-12 11:09
**Missing Cargo** objective Pick-up _The informant's intelligence folder on Customs_ is on **Lighthouse**

**Comment by ambassador86** [comment] 2022-01-24 06:23
For "Energy Crisis" I can confirm that the level requirement is 25.

**Comment by Shebuka** [comment] 2022-07-09 09:15
This must be mostly done with merging of #262

**Closed** 2022-07-09 17:09 UTC
Labels: help wanted
